### ISSUE TITLE
idea: hyperxify

### ISSUE THREAD

**Issue by yoshuawuyts** [substack/hyperx#11]
`mithril` has [mithrilify](https://github.com/sectore/mithrilify) and `riot.js` has [riotify](https://github.com/jhthorsen/riotify), perhaps we could have a `hyperxify` for `hyperx`?

This would save a flat `5kb` minified / unminified per bundle, and some execution time too.

I'm currently not working on frontend stuff, so posting this here in case anyone has some spare time and reckons it'd be fun to build :sparkles:

__edit:__ also worth noting: this removes the hard dependency on multiline string support available in browsers; pretty useful when targeting older systems!

**Comment by substack** [comment]
Done: https://github.com/substack/hyperxify

**Comment by yoshuawuyts** [comment]
brilliant! :fire::fire::fire:

**Comment by colingourlay** [comment]
Bloody marvelous
