### ISSUE TITLE
SVG Support?

### ISSUE THREAD

**Issue by shama** [substack/hyperx#18]
Would you be open to a PR adding SVG self closing tags? Or a PR that exposes the [self closing tags](https://github.com/substack/hyperx/blob/master/index.js#L219) so one could supply their own?

Such as:
```js
var hyperx = require('hyperx')
var hx = hyperx(function (tag, props, children) {
  /* ... turn into thing ... */
}, {
  selfClosingTags: ['circle', /* ... */]
})

var circle = hx`<svg viewBox="0 0 100 100">
  <circle r="${r}" />
</svg>`
```

[Here is a good list of svg elements](https://github.com/tbranyen/diffhtml/blob/master/lib/svg.js#L2). Thanks!

**Comment by yoshuawuyts** [comment]
I'm +1 on having SVG support land; not particularly in favor of adding custom tag declarations

**Comment by substack** [comment]
automatic svg support would be great

**Comment by shama** [comment]
Cool! I'll work on a PR using [svg-tags](https://github.com/element-io/svg-tags) for the list of supported tags.
