### ISSUE TITLE
Support for virtual-dom style object

### ISSUE THREAD

**Issue by vorg** [substack/hyperx#3]
From what I understand `virtual-dom` expects `style` property as [an object](https://github.com/Matt-Esch/virtual-dom/blob/master/docs/vnode.md#propertiesclassname-vs-propertiesattributesclass) while in `hyperx` this happens:

```javascript
var tree = hx`<div style=${{color:'red'}}>`
console.log(tree);
//[Log] VirtualNode {tagName: "DIV", properties: {style: "[object Object]"}...
```

**Comment by substack** [comment]
fixed in 1.0.3 and I added this use case to the tests
