### ISSUE TITLE
Example with properties not working?

### ISSUE THREAD

**Issue by vorg** [substack/hyperx#4]
```javascript
var vdom = require('virtual-dom')
var hyperx = require('hyperx')
var hx = hyperx(vdom.h)
var title = 'hello';
var tree = hx`<h1 y="ab${1+2}cd">hello ${title}!</h1><div style=${{color:'red'}}>`
console.log(vdom.create(tree).toString())
```

In node.js

```javascript
//<h1 y="ab3cd">hello bla!</h1>
```

In FF, Chrome, Saf on OSX
```javascript
//[object HTMLHeadingElement]
```

Also in the browser the resulting DOM doesn't have `y` property.

**Comment by substack** [comment]
This is because there is no container element for the tree. There are 2 elements, and hyperx only uses the first one. Should this be an error? What does jsx do in this case?

**Comment by yoshuawuyts** [comment]
I think it's reasonable to throw an error in this case, as the alternative is a non-explicit error. I don't know what `jsx` does.

**Comment by substack** [comment]
Here's what jsx does:

```
$ cat x.js 
console.log(<div>one</div><div>two</div>)
$ browserify -t [ babelify --presets=react ] x.js
SyntaxError: /home/substack/projects/hyperx/test/x.js: Adjacent JSX elements must be wrapped in an enclosing tag (1:26)
> 1 | console.log(<div>one</div><div>two</div>)
    |                           ^
```

**Comment by substack** [comment]
added an exception for this case with a test in 1.0.4

**Comment by vorg** [comment]
1.0.4 actually fixes the multiple root issue but that wasn't my problem. The copy pasted code should be without div:

```javascript
var title = 'hello';
var tree = hx`<h1 y="ab${1+2}cd">hello ${title}!</h1>`
```

So the problem is that `y` property doesn't show up in the browser (sorry i should have been more clear) and all i get is.

```html
<h1>hello hello</h1>
```

Node works fine somehow..

I believe it's because `virtual-dom` expects `y` to be in `properties: { attributes: { y: "ab3cd" }}` ?
