### ISSUE TITLE
Feature: adding spread like operator

### ISSUE THREAD

**Issue by SilentCicero** [substack/hyperx#46]
In JSX you can use spread naturally `<MyReactComponent ...props>`. I think for hyperx we should support a simple spread operator: `<MyHyperxComponent ...${props}>`.

I added this already by overriding my `createElement` function for `yo-yo`, works great and is super useful. A great little feature. The notation is different enough that it shouldn't effect existing hyperx components, but is super useful for building higher level components that are essentially bypasses.

The only other way to do this is by overriding the createElement methods of other libs like yo-yo and bel. Not very nice really.

Love hyperx, best.

**Comment by jbucaran** [comment]
This would be most useful to have.

**Comment by JamesKyburz** [comment]
We already have this feature, no spread is needed though.

https://github.com/substack/hyperx/blob/master/test/key.js#L46

**Comment by jbucaran** [comment]
Great to know! Thanks @JamesKyburz, I didn't know.

**Comment by SilentCicero** [comment]
Wow, awesome thanks @JamesKyburz maybe we should add this to the ReadMe or make it more clear in the docs.
