### ISSUE TITLE
Leading and trailing whitespace

### ISSUE THREAD

**Issue by almost** [substack/hyperx#6]
Leading and trailing whitespace currently gives an error about only having one root component. For example:
```
hx`
  <div>Hello</div>
`;
```

Will result in an error. I think it would be a good idea to add code that removes leading and trailing whitespace IF there is a component in between them. I can send through a PR if you think that's a good idea.

**Comment by davegomez** [comment]
That will change the original behaviour of the ES6 template strings. Is not a very good idea in my opinion.

**Comment by almost** [comment]
We're generating trees of virtual DOM elements here which is already totally different from untagged template strings. I'm suggesting we take a behavior that is currently "crash weirdly" and make "do something useful" :)

**Comment by maxkueng** [comment]
I was also expecting it to trim trailing and leading white space and ran in to the same error.

**Comment by yoshuawuyts** [comment]
I agree that whitespace leading / trailing newlines shouldn't cause errors; @almost I reckon if you put out a PR it'd be appreciated.

**Comment by almost** [comment]
I've created a PR

**Comment by substack** [comment]
fixed in 1.0.5
